#!/bin/bash

alias create-base="php bin/console doctrine:schema:create"
alias drop-base="php bin/console doctrine:schema:drop --force"

alias comma-create-products="php bin/console app:create-products"
alias comma-create-carriers="php bin/console app:create-carriers"
alias comma-create-orders="php bin/console app:create-orders"

alias comma-create="comma-create-products; comma-create-carriers; comma-create-orders"

alias run-dev="drop-base; create-base; comma-create"
