parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\ORM\EntityManager: "@doctrine.orm.default_entity_manager"

    App\Application\Shared\Controller\:
        resource: '../src/Application/Shared/Controller'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
